### ISSUE TITLE
If you have collapsed rows already created then upon activating the plugin you can't expand them

### ISSUE THREAD

**Issue by skrivener** [JamesParkNINJA/acf-repeater-tabs#2]
Workaround is to deactivate (the whole repeater tabs plugin, I found only turning repeater tabs off made my repeater fields completely inaccessible) and expand then reactivate, or to recreate them as they are expanded by default. It would be nice if this (awesome) plugin could play nicely with allowing collapse/expand also.

**Comment by JamesParkNINJA** [comment]
I'll have a look asap and see if I can work it in, thanks for highlighting!

**Comment by JamesParkNINJA** [comment]
Hi again @skrivener just wondering if you could highlight your repeater tab setup?

When my tabs are collapsed without the plugin, they are still expandable when the plugin is active.

What style of repeater are you using? (Eg. Table, Block, Row)?
