### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasAttribute' of null

### ISSUE THREAD

**Issue by kkerley** [JamesParkNINJA/acf-repeater-tabs#3]
` at global-shortcut.js:10`

On WordPress 4.8 using ACF 5.6.0. Looks like something must've changed with ACF since your last update preventing this from working currently. :(

**Comment by JamesParkNINJA** [comment]
I did notice there was a new version out, I'll look into the differences!
(Hopefully it hasn't changed _too_ much!)

**Comment by kkerley** [comment]
Below the the fieldset if it helps you at all with troubleshooting. It's a reasonably complex repeater with a nested repeater depending on the Content Type selected initially.
[acf-export-2017-08-02.json.zip](https://github.com/JamesParkNINJA/acf-repeater-tabs/files/1194286/acf-export-2017-08-02.json.zip)

**Comment by JamesParkNINJA** [comment]
Hi again @kkerley - not able to recreate your issue on WP 4.8.1, with ACF 5.6.0 with my latest build of the repeater tabs plugin. 

I have fixed two other little bugs in the meantime which may have inadvertantly fixed your issue too.

Could you update to the new version of the plugin, and if the issue's still happening, could you let me know any other differences there might be, such as browser, browser version, etc?

Thanks!
J

**Comment by kkerley** [comment]
I don't know what to tell you...I'm using the FoundationPress starter theme but that has no impact on the backend at all. I disabled all other plugins so that only ACF Pro 5.6.0 and your updated plugin were on and when I try to edit an existing page with a number of repeater elements or attempt to add a new page and use this plugin, it doesn't work. The tabs stack on top of one another so there's no way to access any one but the current/last one. The JS errors are gone from the console but something's clearly still not functioning correctly. 

I've attached some screenshots of what I'm seeing to better illustrate but without any console errors I don't know what could possibly be wrong. :( 

![screenshot 2017-08-05 13 00 50](https://user-images.githubusercontent.com/136047/28997996-9912adb0-79de-11e7-92d1-677455b773b3.png)
![screenshot 2017-08-05 13 00 45](https://user-images.githubusercontent.com/136047/28997997-9913040e-79de-11e7-97f0-c71cad011824.png)
![screenshot 2017-08-05 13 00 40](https://user-images.githubusercontent.com/136047/28997995-991283b2-79de-11e7-933a-eb517637186f.png)
![screenshot 2017-08-05 12 58 55](https://user-images.githubusercontent.com/136047/28997999-991a61ea-79de-11e7-8eb8-ffbcbe931b29.png)
![screenshot 2017-08-05 12 58 20](https://user-images.githubusercontent.com/136047/28997998-991625a8-79de-11e7-9605-11773922f1d3.png)

Your plugin sounds like it's very helpful when it works but I'm sadly unable to get it working. Thanks anyway.

**Comment by JamesParkNINJA** [comment]
Hi again @kkerley 

Think I've encountered this bug before, I'll keep looking into it.

Could you let me know if you've turned on the "Activate Repeater Tabs" part in the field group settings page for your repeater?

If not, could you set it to "Vertical" and let me know if that helps?

Best,
J

**Comment by kkerley** [comment]
I had that enabled and was seeing the above issues. After disabling your plugin and re-enabling, I again set "Vertical" for the tabs option and now it appears your plugin is displaying correctly!

However, I updated to ACF Pro 5.6.1 and now I'm getting this error using either the ACF button or your plugin's button to add a new repeater tab:

`jpn_acf_tabs.js?ver=1.0.0:14 Uncaught TypeError: $ is not a function
    at a.fn.init.jQuery.fn.clone (jpn_acf_tabs.js?ver=1.0.0:14)
    at Object.duplicate (acf-input.min.js?ver=5.6.1:1)
    at Object.add (acf-pro-input.min.js?ver=5.6.1:1)
    at Object._add (acf-pro-input.min.js?ver=5.6.1:1)
    at HTMLAnchorElement.<anonymous> (acf-input.min.js?ver=5.6.1:1)
    at HTMLDocument.dispatch (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3)
    at HTMLDocument.r.handle (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3)`

**Comment by JamesParkNINJA** [comment]
Hi again @kkerley !

I've created a new version of the plugin (v3.7.3), which should now be fully compatible with v5.6.1.

Could you try this, and reactivate and let me know how you get on? :)

Best,
J

**Comment by kkerley** [comment]
Thanks for your continued work and quick responses! I installed 3.8 and tested...I'm able to drag-and-drop existing tabs to change order but I'm getting that same jQuery error posted above whenever I try to add a new tab either via the button your plugin adds below the tabs or using the built-in ACF button to add a new repeater instance. :(

**Comment by JamesParkNINJA** [comment]
Hmm quite puzzling, @kkerley !

Are you using the built-in version of jQuery packaged with WordPress?

Could possibly be a compatibility issue with one of your other plugins, or something in your functions.php too.

Best,
J

**Comment by kkerley** [comment]
It's version 1.12.1 in the admin area. No changes have been made to that and the only plugins I have enabled are ACF Pro 5.6.1 and yours. 

Came back today just now to test again and suddenly it's working so many caches hadn't cleared? I don't know...very weird. But it appears the issue is resolved. THANK YOU!

**Comment by JamesParkNINJA** [comment]
Glad to hear! Cacheing is my worst enemy ;)
Enjoy!
