### ISSUE TITLE
Minor Visual Issue when 'Collapsed' Option is used

### ISSUE THREAD

**Issue by CFusion** [JamesParkNINJA/acf-repeater-tabs#6]
![image](https://user-images.githubusercontent.com/1655727/29099200-1a6dafbe-7ca4-11e7-8ead-56e971caaccb.png)

**Comment by JamesParkNINJA** [comment]
Hi there @CFusion 

Could you explain the process of the error a little more please, I'm not quite sure what I'm looking at!

(All the collapse options I have seem to work fine).

Best,
J

**Comment by JamesParkNINJA** [comment]
Hi again @CFusion ,

Sorry, found what you were talking about, never actually used that feature before in all my years with ACF hah!

Added in a simple click to collapse/show rows.

![tabs](https://user-images.githubusercontent.com/6178652/29132349-d60eed18-7d27-11e7-9f38-9f2f40d0751a.gif)

Best,
J
